HTTP/1.1 500 Internal Server Error
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: https:; font-src 'self' data:; connect-src 'self' https: wss:; frame-ancestors 'none'; base-uri 'self'; form-action 'self'
Referrer-Policy: strict-origin-when-cross-origin
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
set-cookie: sb-user-id=30d779dc-247c-49b5-8ab6-0c3c019443f1; Path=/
vary: RSC, Next-Router-State-Tree, Next-Router-Prefetch
content-type: application/json
Date: Wed, 08 Apr 2026 06:34:51 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Transfer-Encoding: chunked

